import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { Inter } from 'next/font/google'
import NavBar from '@/app/components/common/NavBar'
import AuthProvider from '@/app/contexts/AuthProvider'
import { UserLocationProvider } from '@/app/contexts/UserLocation'
import { MapCoordinateProvider } from '@/app/contexts/MapCoordinate'

import './globals.css'

const font = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: 'Taxi GO App',
  description: 'Generated by create next app',
}

type ReactChildrenNode = {
  children: React.ReactNode
}

export default async function RootLayout({ children }: ReactChildrenNode) {
  return (
    <html lang="en">
      <body className={font.className}>
        <AuthProvider>
          <UserLocationProvider>
            <MapCoordinateProvider>
              <NavBar />
              {children}
            </MapCoordinateProvider>
          </UserLocationProvider>
        </AuthProvider>
      </body>
    </html >
  )
}
